language: node_js
node_js:
    - "8"
    - "10"
    - "11"
    - "12"
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
    - xvfb
before_script:
    - npm i -g typescript@next
    - export DISPLAY=:99.0
install:
    - npm install
    - npm run bootstrap
script:
    - npm run travis
after_script:
    - npm run coveralls

